import type { Profile, LinkItem, SocialLink } from './types';

export const initialProfile: Profile = {
  id: 'main',
  name: 'Duy Nguyen /zuey/',
  handle: '@goonnguyen',
  email: 'hi@zuey.me',
  avatar_url: 'https://cdn.zuey.me/avatar.png',
  intro_en: '"F*ck Around & Find Out" Specialist 😎 CTO/Co-founder@TOPGROUP, DIGITOP, XINCHAO Live Music, AgentKit & NextLevelBuilder. Founder of "Build in Public VN" Community (Facebook).',
  intro_vi: 'Chuyên gia "F*ck Around & Find Out" 😎 CTO/Đồng sáng lập@TOPGROUP, DIGITOP, XINCHAO Live Music, AgentKit & NextLevelBuilder. Nhà sáng lập cộng đồng "Build in Public VN" (Facebook).',
  theme: 'ivory',
};

export const initialSocials: SocialLink[] = [
  { id: 'ig', platform: 'instagram', url: 'https://www.instagram.com/imzuey', label: 'Instagram' },
  { id: 'tiktok', platform: 'tiktok', url: 'https://www.tiktok.com/@mrgoonvn', label: 'TikTok' },
  { id: 'threads', platform: 'threads', url: 'https://www.threads.com/@imzuey', label: 'Threads' },
  { id: 'youtube', platform: 'youtube', url: 'https://youtube.com/@imzuey', label: 'YouTube' },
  { id: 'fb', platform: 'facebook', url: 'https://fb.com/mrgoonie', label: 'Facebook' },
  { id: 'x', platform: 'x', url: 'https://x.com/goon_nguyen', label: 'X (Twitter)' },
  { id: 'email', platform: 'email', url: 'mailto:hi@zuey.me', label: 'Email' },
];

export const initialLinks: LinkItem[] = [
  // Blogs
  {
    id: 'blog-en',
    section: 'blogs',
    title_en: '✍️ FA&FO Specialist - English',
    title_vi: '✍️ Chuyên gia FA&FO - Tiếng Anh',
    subtitle_en: 'Substack Newsletter on AI engineering, products & experiments',
    subtitle_vi: 'Bản tin Substack về kỹ nghệ AI, sản phẩm & thử nghiệm',
    url: 'https://faafospecialist.substack.com/',
    icon: 'substack',
    order_index: 1,
    is_active: true,
    click_count: 320,
  },
  {
    id: 'blog-vi',
    section: 'blogs',
    title_en: '✍️ My Solo Playbook - Vietnamese',
    title_vi: '✍️ Sổ tay Solo Builder - Tiếng Việt',
    subtitle_en: 'Hành trình xây dựng sản phẩm và chia sẻ thực chiến',
    subtitle_vi: 'Hành trình xây dựng sản phẩm và chia sẻ thực chiến',
    url: 'https://goonnguyen.substack.com/',
    icon: 'substack',
    order_index: 2,
    is_active: true,
    click_count: 512,
  },

  // Companies ("Found by me!")
  {
    id: 'company-topgroup',
    section: 'companies',
    title_en: 'The Outstanding Production Group (T.O.P Viet Nam)',
    title_vi: 'The Outstanding Production Group (T.O.P Việt Nam)',
    subtitle_en: 'Leading production & creative technology conglomerate',
    subtitle_vi: 'Tập đoàn sản xuất & công nghệ sáng tạo hàng đầu',
    url: 'https://wearetopgroup.com',
    icon: 'topgroup',
    order_index: 1,
    is_active: true,
    click_count: 890,
  },
  {
    id: 'company-xinchao',
    section: 'companies',
    title_en: 'Xin Chào Live Music - A Professional Music Organization Platform',
    title_vi: 'Xin Chào Live Music - Nền tảng tổ chức biểu diễn âm nhạc chuyên nghiệp',
    subtitle_en: 'Connecting top Vietnamese artists and global music experiences',
    subtitle_vi: 'Kết nối nghệ sĩ Việt Nam hàng đầu và trải nghiệm âm nhạc quốc tế',
    url: 'https://xinchao.world',
    icon: 'xinchao',
    order_index: 2,
    is_active: true,
    click_count: 670,
  },
  {
    id: 'company-digitop',
    section: 'companies',
    title_en: 'Digitop - Crafting Award-winning Digital Assets',
    title_vi: 'Digitop - Thiết kế và phát triển tài sản số đạt giải thưởng',
    subtitle_en: 'Digital agency & AI-driven development house',
    subtitle_vi: 'Digital agency và công ty công nghệ chuyên sâu AI',
    url: 'https://digitop.ai',
    icon: 'digitop',
    order_index: 3,
    is_active: true,
    click_count: 745,
  },
  {
    id: 'company-nextlevel',
    section: 'companies',
    title_en: 'NEXT LEVEL BUILDER',
    title_vi: 'NEXT LEVEL BUILDER',
    subtitle_en: 'Venture builder turning ideas into high-velocity products',
    subtitle_vi: 'Venture builder biến ý tưởng thành sản phẩm đột phá',
    url: 'https://nextlevelbuilder.io',
    icon: 'nextlevel',
    order_index: 4,
    is_active: true,
    click_count: 420,
  },
  {
    id: 'company-tose',
    section: 'companies',
    title_en: 'TOSE - Fast, Reliable Cloud Infrastructure',
    title_vi: 'TOSE - Hạ tầng đám mây tốc độ cao và ổn định',
    subtitle_en: 'Modern hosting and developer cloud platform',
    subtitle_vi: 'Nền tảng lưu trữ và hạ tầng đám mây cho lập trình viên',
    url: 'https://tose.sh',
    icon: 'tose',
    order_index: 5,
    is_active: true,
    click_count: 380,
  },
  {
    id: 'company-bipvn',
    section: 'companies',
    title_en: '"Build in Public VN" Community',
    title_vi: 'Cộng đồng "Build in Public VN"',
    subtitle_en: 'The #1 community for indie hackers and makers in Vietnam',
    subtitle_vi: 'Cộng đồng #1 dành cho indie hacker và nhà sáng tạo tại Việt Nam',
    url: 'https://bip.vn',
    icon: 'bipvn',
    order_index: 6,
    is_active: true,
    click_count: 1450,
  },

  // Products
  {
    id: 'prod-agentkit',
    section: 'products',
    title_en: 'AgentKit.best (formerly ClaudeKit.cc)',
    title_vi: 'AgentKit.best (tiền thân ClaudeKit.cc)',
    subtitle_en: 'The complete AI engineering framework to build autonomous agents',
    subtitle_vi: 'Khung kỹ nghệ AI hoàn chỉnh để xây dựng và vận hành AI agent',
    url: 'https://agentkit.best',
    icon: 'agentkit',
    order_index: 1,
    is_active: true,
    click_count: 1210,
  },
  {
    id: 'prod-dewee',
    section: 'products',
    title_en: 'Dewee.sh (formerly GoClaw.sh)',
    title_vi: 'Dewee.sh (tiền thân GoClaw.sh)',
    subtitle_en: 'Enterprise AI agent runtime platform for human-AI teamwork',
    subtitle_vi: 'Nền tảng runtime AI agent doanh nghiệp cho sự cộng tác người - AI',
    url: 'https://dewee.sh',
    icon: 'dewee',
    order_index: 2,
    is_active: true,
    click_count: 980,
  },
  {
    id: 'prod-goclaw',
    section: 'products',
    title_en: 'GoClaw.sh',
    title_vi: 'GoClaw.sh',
    subtitle_en: 'High-performance Go runtime gateway for distributed agents',
    subtitle_vi: 'Gateway runtime Go hiệu năng cao cho hệ thống agent phân tán',
    url: 'https://goclaw.sh',
    icon: 'goclaw',
    order_index: 3,
    is_active: true,
    click_count: 430,
  },
  {
    id: 'prod-tose',
    section: 'products',
    title_en: 'tose.sh',
    title_vi: 'tose.sh',
    subtitle_en: 'Edge cloud deployment and serverless orchestration',
    subtitle_vi: 'Hạ tầng deploy edge và điều phối serverless',
    url: 'https://tose.sh',
    icon: 'tose',
    order_index: 4,
    is_active: true,
    click_count: 310,
  },
  {
    id: 'prod-indieboosting',
    section: 'products',
    title_en: 'IndieBoosting.com',
    title_vi: 'IndieBoosting.com',
    subtitle_en: 'The 1st SaaS distribution network for indie hackers',
    subtitle_vi: 'Mạng lưới phân phối SaaS số 1 cho các nhà sáng lập',
    url: 'https://indieboosting.com',
    icon: 'indieboosting',
    order_index: 5,
    is_active: true,
    click_count: 620,
  },
  {
    id: 'prod-uupm',
    section: 'products',
    title_en: 'uupm.cc (UI UX Pro Max Skill)',
    title_vi: 'uupm.cc (Kỹ năng UI UX Pro Max)',
    subtitle_en: 'AI skill that designs and crafts world-class web and mobile interfaces',
    subtitle_vi: 'Kỹ năng AI thiết kế giao diện web & mobile chuẩn quốc tế',
    url: 'https://uupm.cc',
    icon: 'uupm',
    order_index: 6,
    is_active: true,
    click_count: 870,
  },
  {
    id: 'prod-agentwiki',
    section: 'products',
    title_en: 'AgentWiki.cc',
    title_vi: 'AgentWiki.cc',
    subtitle_en: 'Static documentation and knowledge publishing platform for AI agents',
    subtitle_vi: 'Nền tảng xuất bản tài liệu tĩnh và tri thức cho AI agents',
    url: 'https://agentwiki.cc',
    icon: 'agentwiki',
    order_index: 7,
    is_active: true,
    click_count: 390,
  },
  {
    id: 'prod-agentbrain',
    section: 'products',
    title_en: 'AgentBrain.sh',
    title_vi: 'AgentBrain.sh',
    subtitle_en: 'Shared memory and semantic intelligence layer for AI swarms',
    subtitle_vi: 'Bộ nhớ dùng chung và lớp trí tuệ ngữ nghĩa cho đội ngũ AI',
    url: 'https://agentbrain.sh',
    icon: 'agentbrain',
    order_index: 8,
    is_active: true,
    click_count: 340,
  },
  {
    id: 'prod-skillx',
    section: 'products',
    title_en: 'SkillX.sh',
    title_vi: 'SkillX.sh',
    subtitle_en: 'Open agent skill registry and instant execution runtime',
    subtitle_vi: 'Kho lưu trữ kỹ năng mở và môi trường thực thi tức thì cho agent',
    url: 'https://skillx.sh',
    icon: 'skillx',
    order_index: 9,
    is_active: true,
    click_count: 290,
  },
  {
    id: 'prod-findyourai',
    section: 'products',
    title_en: 'FindYourAI.tools',
    title_vi: 'FindYourAI.tools',
    subtitle_en: 'Curated directory of high-productivity AI tools and prompt systems',
    subtitle_vi: 'Danh bạ tuyển chọn công cụ AI năng suất cao và hệ thống prompt',
    url: 'https://findyourai.tools',
    icon: 'findyourai',
    order_index: 10,
    is_active: true,
    click_count: 530,
  },
  {
    id: 'prod-vidcap',
    section: 'products',
    title_en: 'VidCap.zuey.me',
    title_vi: 'VidCap.zuey.me',
    subtitle_en: 'AI video captioning and viral subtitle generation',
    subtitle_vi: 'Tự động tạo phụ đề video và phụ đề viral bằng AI',
    url: 'https://vidcap.zuey.me',
    icon: 'vidcap',
    order_index: 11,
    is_active: true,
    click_count: 410,
  },
  {
    id: 'prod-reviewweb',
    section: 'products',
    title_en: 'ReviewWeb.site',
    title_vi: 'ReviewWeb.site',
    subtitle_en: 'Automated SEO audit, backlink intelligence and site health diagnostic',
    subtitle_vi: 'Kiểm toán SEO tự động, phân tích backlink và chuẩn đoán website',
    url: 'https://reviewweb.site',
    icon: 'reviewweb',
    order_index: 12,
    is_active: true,
    click_count: 480,
  },
];
